#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AsistentePagos.Resource", IsApplication=true)]

namespace AsistentePagos
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_light_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gato_developer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int microphone_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int une_icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int imageViewItem = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int imageViewMicrophone = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int linearLayoutDescription = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int linearLayoutHeader = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int linearLayoutItem = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int listViewInvoices = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int logo_pagosapp = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int textViewDescriptionItem = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textViewDueDate = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int textViewPaymentValue = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textViewTitle = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int webView1 = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int InvoiceListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int InvoicesList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
